# Generated by Django 2.0.5 on 2018-06-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surl', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('abstract', models.TextField()),
                ('subject', models.CharField(max_length=150)),
            ],
        ),
    ]
